openapi: 3.0.3
info:
  title:  vasco-bank-pagamento- OpenAPI 3.0
  description: ''
  version: 1.0.11

servers:
  - url: https:/vasco-bank-pagamento/api/v1
tags:
  - name: pagamento
    description: todos os acessos para formas de pagamentos e transferencias
paths:
  /pagamento/{userId}:
    get:
      tags:
        - pagamento
      summary: Retorna a conta do usuario
      description: Returns um map da conta do usuario
      operationId: getContaCorrentById
      parameters:
        - name: userId
          in: path
          description: ID do usuario
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pagamento'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Pagamento'
        '400':
          description: Invalid ID supplied
        '404':
          description: conta not found
      security:
        - api_key: []
  /pagamento/{userId}/saldo:
    get:
      tags:
        - pagamento
      summary: Place an order for a pet
      description: Place a new order in the store
      operationId: placeOrder
      parameters:
        - name: userId
          in: path
          description: ID do usuario
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/saldo'
        '405':
          description: Invalid input
          
  /contaCorrente/saldo:
    post:
      tags:
        - contaCorrente
      summary: Place an order for a pet
      description: Place a new order in the store
      operationId: saldo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/saldo'
          application/xml:
            schema:
              $ref: '#/components/schemas/saldo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/saldo'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/saldo'
        '405':
          description: Invalid input
  /pagamento/pix:
    post:
      tags:
        - pagamento
      summary: Realizar Pix
      description: Fazer um pagamento por pix
      operationId: PagamentoPix
      parameters:
        - name: ChavePix
          in: path
          description: Chave pix do alvo
          required: true
          schema:
            type: string
        - name: ValorTransferencia
          in: path
          description: Valor a ser transferido
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pix'          
            application/xml:
              schema:
                $ref: '#/components/schemas/pix'
        '404':
          description: Chave não encontrada
  /pagamento/boleto:
    post:
      tags:
        - pagamento
      summary: Realiza um pagamento por boleto
      description: Add a new pet to the store
      operationId: PagarPorBoleto
      requestBody:
        description: Pega 2 contas uma emissora e outra alvo com o valor e data de vencimento e transfere
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/boleto'
          application/xml:
            schema:
              $ref: '#/components/schemas/boleto'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/boleto'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/boleto'          
            application/xml:
              schema:
                $ref: '#/components/schemas/boleto'
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  /pagamento/intrabanco:
    post:
      tags:
        - pagamento
      summary: Faz a Transferencia entre bancos
      description: Faz a Transferencia entre bancos
      operationId: TransferenciaEntreBancos
      parameters:
        - name: status
          in: query
          description: Faz a Transferencia entre 2 contas de bancos diferentes usando o ID das contas(emissora e alvo), o id do banco do alvo e uma taxa
          required: true
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferenciaEntreBanco'
          application/xml:
            schema:
              $ref: '#/components/schemas/TransferenciaEntreBanco'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TransferenciaEntreBanco'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferenciaEntreBanco'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferenciaEntreBanco'
        '400':
          description: Invalid status value
      security:
        - petstore_auth:
            - write:pets
            - read:pets

  
    
components:
  schemas:
    Pagamento:
      type: object
      properties:
        tipoPagamento:
          type: string
          enum:
            - PIX
            - BOLETO
            - PAGCARTAOCREDITO
            - INTRABANCO
            - 
    pix:
      type: object
      properties:
        ChavePixAlvo:
          type: string
          example: '12345679'
        Valor:
          type: number
          example: '24.69'
        Data:
          type: string
          example: '01/05/2023'         
    xml:
      name: Pix
    
    boleto:
      type: object
      properties:
        Valor:
          type: number
          example: 24.69
        ContaAlvo:
          type: string
          example: '12345679'
        ContaOrigem:
          type: string
          example: '987654321'
        DataEmissao:
          type: string
          example: '01/05/2023'
        DataVencimento:
          type: string
          example: '20/05/2023'
        xml:
          name: Boleto

    saldo:
      type: object
      properties:
        idConta: 
          type: integer
          example: 1
        valor:
          type: number
          format: int64
          example: 99.99
      xml:
        name: saldo
        
    extrato:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        dataOperacao:
          type: string
          format: date
        operacao:
          type: string
          enum:
            - PIX
            - BOLETO
            - INTRABANCO
            - PAGCARTAO
      xml:
        name: extrato
        
    PagarComCartaoCredito:
      type: object
      properties:
        ValorPagamentoCartao:
          type: number
          example: 10.10
        idCartao:
          type: string
          example: '292010'
        idConta:
          type: string
          example: '324353'
        Juros:
          type: number
          example: 5.23
      xml:
        name: PagarComCartaoCredito
      
    TransferenciaEntreBanco:
      type: object
      properties:
        ValorTransferencia:
          type: number
          example: 10.10
        ContaAlvo:
          type: string
          example: '292010'
        ContaOrigem:
          type: string
          example: '324353'
        idBanco:
          type: string
          example: '12345'
        Taxa:
          type: number
          example: 2.23
        xml:
          name: TransferenciaEntreBanco

   
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://vasco-bank-conta/api/v1/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header